name: Validar Código TypeScript

on:
  push:
    branches:
      - feature/exercicio-01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Configurar o Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Executar validação do TypeScript
      run: npm run build
